-- insert data into address table
insert into address (id, st_address, city, state, country, zip) values (1, '025 Cordelia Road', 'Omaha', 'Nebraska', 'United States', '68110');
insert into address (id, st_address, city, state, country, zip) values (2, '25 Summer Ridge Junction', 'Toledo', 'Ohio', 'United States', '43699');
insert into address (id, st_address, city, state, country, zip) values (3, '168 Kropf Way', 'Naples', 'Florida', 'United States', '34108');
insert into address (id, st_address, city, state, country, zip) values (4, '613 Oxford Terrace', 'Saint Paul', 'Minnesota', 'United States', '55166');
insert into address (id, st_address, city, state, country, zip) values (5, '62113 Lawn Center', 'Kansas City', 'Missouri', 'United States', '64114');
insert into address (id, st_address, city, state, country, zip) values (6, '502 Mcguire Pass', 'Albany', 'New York', 'United States', '12222');
insert into address (id, st_address, city, state, country, zip) values (7, '49 Cordelia Road', 'Youngstown', 'Ohio', 'United States', '44505');
insert into address (id, st_address, city, state, country, zip) values (8, '39 Elka Place', 'Denver', 'Colorado', 'United States', '80249');
insert into address (id, st_address, city, state, country, zip) values (9, '10 Kim Drive', 'Houston', 'Texas', 'United States', '77281');
insert into address (id, st_address, city, state, country, zip) values (10, '06 Colorado Alley', 'Birmingham', 'Alabama', 'United States', '35205');
insert into address (id, st_address, city, state, country, zip) values (11, '39142 Dawn Lane', 'San Diego', 'California', 'United States', '92145');
insert into address (id, st_address, city, state, country, zip) values (12, '3763 Ridgeview Street', 'New Orleans', 'Louisiana', 'United States', '70187');
insert into address (id, st_address, city, state, country, zip) values (13, '91803 Artisan Junction', 'Denver', 'Colorado', 'United States', '80270');
insert into address (id, st_address, city, state, country, zip) values (14, '43666 Westridge Trail', 'Des Moines', 'Iowa', 'United States', '50335');
insert into address (id, st_address, city, state, country, zip) values (15, '68364 Pennsylvania Lane', 'Orlando', 'Florida', 'United States', '32830');
insert into address (id, st_address, city, state, country, zip) values (16, '80 Mockingbird Place', 'South Bend', 'Indiana', 'United States', '46634');
insert into address (id, st_address, city, state, country, zip) values (17, '6952 Sunfield Lane', 'Denver', 'Colorado', 'United States', '80249');
insert into address (id, st_address, city, state, country, zip) values (18, '03 Glacier Hill Center', 'Atlanta', 'Georgia', 'United States', '31119');
insert into address (id, st_address, city, state, country, zip) values (19, '320 Jenna Plaza', 'San Antonio', 'Texas', 'United States', '78210');
insert into address (id, st_address, city, state, country, zip) values (20, '05808 Milwaukee Avenue', 'Washington', 'District of Columbia', 'United States', '20088');
insert into address (id, st_address, city, state, country, zip) values (21, '15 Hallows Crossing', 'Little Rock', 'Arkansas', 'United States', '72209');
insert into address (id, st_address, city, state, country, zip) values (22, '9560 Thierer Circle', 'Jacksonville', 'Florida', 'United States', '32204');
insert into address (id, st_address, city, state, country, zip) values (23, '322 Green Street', 'Charlottesville', 'Virginia', 'United States', '22903');
insert into address (id, st_address, city, state, country, zip) values (24, '59 Swallow Center', 'New York City', 'New York', 'United States', '10125');
insert into address (id, st_address, city, state, country, zip) values (25, '0 Dexter Court', 'Houston', 'Texas', 'United States', '77255');
insert into address (id, st_address, city, state, country, zip) values (26, '5187 Lerdahl Place', 'Birmingham', 'Alabama', 'United States', '35290');
insert into address (id, st_address, city, state, country, zip) values (27, '839 Sutherland Parkway', 'Rochester', 'New York', 'United States', '14619');
insert into address (id, st_address, city, state, country, zip) values (28, '586 Moulton Way', 'Milwaukee', 'Wisconsin', 'United States', '53215');
insert into address (id, st_address, city, state, country, zip) values (29, '674 Dixon Trail', 'Springfield', 'Illinois', 'United States', '62705');
insert into address (id, st_address, city, state, country, zip) values (30, '6982 Pierstorff Court', 'Springfield', 'Illinois', 'United States', '62764');
insert into address (id, st_address, city, state, country, zip) values (31, '2 Hudson Way', 'Springfield', 'Illinois', 'United States', '62756');
insert into address (id, st_address, city, state, country, zip) values (32, '2 Continental Way', 'Columbia', 'South Carolina', 'United States', '29215');
insert into address (id, st_address, city, state, country, zip) values (33, '42009 Muir Crossing', 'Seattle', 'Washington', 'United States', '98175');
insert into address (id, st_address, city, state, country, zip) values (34, '95 Browning Hill', 'Washington', 'District of Columbia', 'United States', '20508');
insert into address (id, st_address, city, state, country, zip) values (35, '70 Carberry Parkway', 'Rockford', 'Illinois', 'United States', '61105');
insert into address (id, st_address, city, state, country, zip) values (36, '25304 Tennessee Pass', 'Fargo', 'North Dakota', 'United States', '58106');
insert into address (id, st_address, city, state, country, zip) values (37, '734 Harbort Alley', 'Spartanburg', 'South Carolina', 'United States', '29319');
insert into address (id, st_address, city, state, country, zip) values (38, '55 Comanche Pass', 'Sacramento', 'California', 'United States', '94263');
insert into address (id, st_address, city, state, country, zip) values (39, '20919 Hayes Terrace', 'Pasadena', 'California', 'United States', '91186');
insert into address (id, st_address, city, state, country, zip) values (40, '58 Mcguire Place', 'Boise', 'Idaho', 'United States', '83716');
insert into address (id, st_address, city, state, country, zip) values (41, '4307 Graceland Junction', 'Salt Lake City', 'Utah', 'United States', '84152');
insert into address (id, st_address, city, state, country, zip) values (42, '8 Vahlen Road', 'Lake Worth', 'Florida', 'United States', '33467');
insert into address (id, st_address, city, state, country, zip) values (43, '0090 Weeping Birch Point', 'Salt Lake City', 'Utah', 'United States', '84199');
insert into address (id, st_address, city, state, country, zip) values (44, '8 Johnson Circle', 'Tampa', 'Florida', 'United States', '33610');
insert into address (id, st_address, city, state, country, zip) values (45, '29951 Northridge Circle', 'New York City', 'New York', 'United States', '10150');
insert into address (id, st_address, city, state, country, zip) values (46, '6915 Lunder Street', 'Richmond', 'Virginia', 'United States', '23237');
insert into address (id, st_address, city, state, country, zip) values (47, '73099 Southridge Avenue', 'Colorado Springs', 'Colorado', 'United States', '80920');
insert into address (id, st_address, city, state, country, zip) values (48, '93 Express Road', 'Oceanside', 'California', 'United States', '92056');
insert into address (id, st_address, city, state, country, zip) values (49, '870 Larry Street', 'San Antonio', 'Texas', 'United States', '78215');
insert into address (id, st_address, city, state, country, zip) values (50, '96037 6th Terrace', 'Newport Beach', 'California', 'United States', '92662');
insert into address (id, st_address, city, state, country, zip) values (51, '86992 Sachtjen Way', 'Washington', 'District of Columbia', 'United States', '20205');
insert into address (id, st_address, city, state, country, zip) values (52, '248 Norway Maple Terrace', 'Akron', 'Ohio', 'United States', '44329');
insert into address (id, st_address, city, state, country, zip) values (53, '86824 Marquette Lane', 'Dallas', 'Texas', 'United States', '75265');
insert into address (id, st_address, city, state, country, zip) values (54, '66583 Prairieview Park', 'Nashville', 'Tennessee', 'United States', '37240');
insert into address (id, st_address, city, state, country, zip) values (55, '4949 Rusk Parkway', 'Boston', 'Massachusetts', 'United States', '02104');
insert into address (id, st_address, city, state, country, zip) values (56, '36 Longview Park', 'Columbia', 'Missouri', 'United States', '65211');
insert into address (id, st_address, city, state, country, zip) values (57, '47131 Delaware Circle', 'Spokane', 'Washington', 'United States', '99205');
insert into address (id, st_address, city, state, country, zip) values (58, '66995 Sauthoff Parkway', 'Seattle', 'Washington', 'United States', '98185');
insert into address (id, st_address, city, state, country, zip) values (59, '9276 Nobel Lane', 'Baltimore', 'Maryland', 'United States', '21239');
insert into address (id, st_address, city, state, country, zip) values (60, '85146 Luster Circle', 'Charlotte', 'North Carolina', 'United States', '28247');
insert into address (id, st_address, city, state, country, zip) values (61, '8 Loomis Place', 'Kalamazoo', 'Michigan', 'United States', '49006');
insert into address (id, st_address, city, state, country, zip) values (62, '7 Buhler Plaza', 'New Haven', 'Connecticut', 'United States', '06505');
insert into address (id, st_address, city, state, country, zip) values (63, '6699 Sunnyside Drive', 'Brooklyn', 'New York', 'United States', '11231');
insert into address (id, st_address, city, state, country, zip) values (64, '66 Columbus Parkway', 'Cleveland', 'Ohio', 'United States', '44185');
insert into address (id, st_address, city, state, country, zip) values (65, '46394 Steensland Circle', 'Arlington', 'Virginia', 'United States', '22217');
insert into address (id, st_address, city, state, country, zip) values (66, '692 Ohio Park', 'Knoxville', 'Tennessee', 'United States', '37919');
insert into address (id, st_address, city, state, country, zip) values (67, '0602 Merchant Lane', 'Dayton', 'Ohio', 'United States', '45454');
insert into address (id, st_address, city, state, country, zip) values (68, '80 Transport Road', 'Bakersfield', 'California', 'United States', '93311');
insert into address (id, st_address, city, state, country, zip) values (69, '59475 Rigney Lane', 'Fort Wayne', 'Indiana', 'United States', '46857');
insert into address (id, st_address, city, state, country, zip) values (70, '62965 Scott Hill', 'Columbia', 'Missouri', 'United States', '65211');
insert into address (id, st_address, city, state, country, zip) values (71, '45 Troy Junction', 'Minneapolis', 'Minnesota', 'United States', '55441');
insert into address (id, st_address, city, state, country, zip) values (72, '0 Northridge Way', 'Memphis', 'Tennessee', 'United States', '38114');
insert into address (id, st_address, city, state, country, zip) values (73, '80112 Kipling Place', 'Chicago', 'Illinois', 'United States', '60691');
insert into address (id, st_address, city, state, country, zip) values (74, '086 Straubel Pass', 'Cleveland', 'Ohio', 'United States', '44111');
insert into address (id, st_address, city, state, country, zip) values (75, '1100 Kenwood Hill', 'Jacksonville', 'Florida', 'United States', '32259');
insert into address (id, st_address, city, state, country, zip) values (76, '41238 Grasskamp Place', 'Tyler', 'Texas', 'United States', '75710');
insert into address (id, st_address, city, state, country, zip) values (77, '26961 Johnson Point', 'Saint Paul', 'Minnesota', 'United States', '55123');
insert into address (id, st_address, city, state, country, zip) values (78, '75 Northwestern Hill', 'Salem', 'Oregon', 'United States', '97312');
insert into address (id, st_address, city, state, country, zip) values (79, '1 Bellgrove Lane', 'Rochester', 'New York', 'United States', '14639');
insert into address (id, st_address, city, state, country, zip) values (80, '3566 Talisman Alley', 'Ocala', 'Florida', 'United States', '34474');
insert into address (id, st_address, city, state, country, zip) values (81, '7008 Mifflin Circle', 'Torrance', 'California', 'United States', '90505');
insert into address (id, st_address, city, state, country, zip) values (82, '13 Alpine Street', 'Tucson', 'Arizona', 'United States', '85732');
insert into address (id, st_address, city, state, country, zip) values (83, '79 Crowley Drive', 'Allentown', 'Pennsylvania', 'United States', '18105');
insert into address (id, st_address, city, state, country, zip) values (84, '4662 Reinke Road', 'Seattle', 'Washington', 'United States', '98166');
insert into address (id, st_address, city, state, country, zip) values (85, '38 Center Park', 'Morgantown', 'West Virginia', 'United States', '26505');
insert into address (id, st_address, city, state, country, zip) values (86, '66 Chive Plaza', 'New Orleans', 'Louisiana', 'United States', '70129');
insert into address (id, st_address, city, state, country, zip) values (87, '5325 Victoria Drive', 'Dallas', 'Texas', 'United States', '75241');
insert into address (id, st_address, city, state, country, zip) values (88, '82042 Roth Center', 'Sacramento', 'California', 'United States', '94237');
insert into address (id, st_address, city, state, country, zip) values (89, '9 Jana Avenue', 'Minneapolis', 'Minnesota', 'United States', '55417');
insert into address (id, st_address, city, state, country, zip) values (90, '5659 Grim Circle', 'Cedar Rapids', 'Iowa', 'United States', '52410');
insert into address (id, st_address, city, state, country, zip) values (91, '4146 Mcguire Place', 'Mount Vernon', 'New York', 'United States', '10557');
insert into address (id, st_address, city, state, country, zip) values (92, '1704 Upham Drive', 'Fort Worth', 'Texas', 'United States', '76162');
insert into address (id, st_address, city, state, country, zip) values (93, '31410 Gerald Center', 'Houston', 'Texas', 'United States', '77025');
insert into address (id, st_address, city, state, country, zip) values (94, '3 Homewood Parkway', 'Orlando', 'Florida', 'United States', '32868');
insert into address (id, st_address, city, state, country, zip) values (95, '02 Lighthouse Bay Place', 'Oklahoma City', 'Oklahoma', 'United States', '73197');
insert into address (id, st_address, city, state, country, zip) values (96, '79 Lerdahl Center', 'Richmond', 'Virginia', 'United States', '23289');
insert into address (id, st_address, city, state, country, zip) values (97, '022 Elka Hill', 'Memphis', 'Tennessee', 'United States', '38143');
insert into address (id, st_address, city, state, country, zip) values (98, '450 Hagan Crossing', 'San Jose', 'California', 'United States', '95108');
insert into address (id, st_address, city, state, country, zip) values (99, '23050 Grover Road', 'Saint Petersburg', 'Florida', 'United States', '33737');
insert into address (id, st_address, city, state, country, zip) values (100, '90 Sommers Parkway', 'Punta Gorda', 'Florida', 'United States', '33982');