-- insert data into application table
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (1, 1, null, '2018-10-30', 'in progress', 1);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (2, 2, null, '2018-05-04', 'complete', 2);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (3, 3, null, '2018-12-03', 'in progress', 3);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (4, 4, null, '2018-09-13', 'complete', 4);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (5, 5, null, '2017-04-28', 'in progress', 5);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (6, 6, null, '2017-05-26', 'complete', 6);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (7, 7, null, '2017-09-23', 'complete', 7);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (8, 8, null, '2018-03-16', 'complete', 8);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (9, 9, null, '2018-06-22', 'complete', 9);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (10, 10, null, '2018-05-12', 'complete', 10);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (11, 11, null, '2018-08-26', 'complete', 11);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (12, 12, null, '2018-06-04', 'complete', 12);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (13, 13, null, '2017-06-14', 'complete', 13);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (14, 14, null, '2017-06-17', 'complete', 14);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (15, 15, null, '2018-05-11', 'complete', 15);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (16, 16, null, '2018-01-11', 'complete', 16);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (17, 17, null, '2018-01-29', 'complete', 17);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (18, 18, null, '2018-02-03', 'complete', 18);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (19, 19, null, '2018-01-03', 'complete', 19);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (20, 20, null, '2018-12-09', 'complete', 20);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (21, 21, null, '2018-01-12', 'complete', 21);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (22, 22, null, '2018-05-15', 'in progress', 22);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (23, 23, null, '2017-02-26', 'complete', 23);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (24, 24, null, '2018-07-27', 'complete', 24);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (25, 25, null, '2017-07-19', 'complete', 25);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (26, 26, null, '2018-11-07', 'complete', 26);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (27, 27, null, '2018-12-13', 'complete', 27);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (28, 28, null, '2018-12-16', 'complete', 28);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (29, 29, null, '2018-09-07', 'complete', 29);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (30, 30, null, '2018-07-19', 'complete', 30);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (31, 31, null, '2018-06-27', 'complete', 31);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (32, 32, null, '2018-09-26', 'in progress', 32);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (33, 33, null, '2018-07-10', 'in progress', 33);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (34, 34, null, '2018-01-07', 'complete', 34);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (35, 35, null, '2018-10-27', 'complete', 35);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (36, 36, null, '2018-11-28', 'in progress', 36);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (37, 37, null, '2018-03-10', 'in progress', 37);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (38, 38, null, '2018-11-15', 'in progress', 38);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (39, 39, null, '2017-03-28', 'in progress', 39);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (40, 40, null, '2018-03-11', 'complete', 40);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (41, 41, null, '2018-07-14', 'complete', 41);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (42, 42, null, '2018-12-15', 'in progress', 42);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (43, 43, null, '2018-10-15', 'in progress', 43);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (44, 44, null, '2017-03-18', 'in progress', 44);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (45, 45, null, '2018-11-30', 'in progress', 45);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (46, 46, null, '2018-06-12', 'complete', 46);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (47, 47, null, '2017-04-20', 'in progress', 47);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (48, 48, null, '2017-03-20', 'in progress', 48);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (49, 49, null, '2018-08-14', 'complete', 49);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (50, 50, null, '2018-02-18', 'in progress', 50);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (51, 51, null, '2017-08-19', 'complete', 51);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (52, 52, null, '2018-03-01', 'complete', 52);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (53, 53, null, '2018-04-15', 'in progress', 53);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (54, 54, null, '2018-09-14', 'complete', 54);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (55, 55, null, '2018-12-18', 'in progress', 55);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (56, 56, null, '2017-01-07', 'complete', 56);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (57, 57, null, '2018-09-10', 'in progress', 57);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (58, 58, null, '2018-09-16', 'in progress', 58);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (59, 59, null, '2018-03-07', 'complete', 59);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (60, 60, null, '2018-09-14', 'complete', 60);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (61, 61, null, '2018-05-02', 'complete', 61);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (62, 62, null, '2018-10-06', 'complete', 62);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (63, 63, null, '2017-01-08', 'in progress', 63);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (64, 64, null, '2018-02-02', 'complete', 64);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (65, 65, null, '2018-05-28', 'in progress', 65);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (66, 66, null, '2018-01-10', 'in progress', 66);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (67, 67, null, '2018-07-19', 'complete', 67);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (68, 68, null, '2018-11-17', 'complete', 68);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (69, 69, null, '2018-03-16', 'complete', 69);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (70, 70, null, '2018-07-29', 'complete', 70);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (71, 71, null, '2018-12-14', 'in progress', 71);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (72, 72, null, '2017-04-07', 'complete', 72);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (73, 73, null, '2017-07-13', 'complete', 73);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (74, 74, null, '2018-12-16', 'complete', 74);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (75, 75, null, '2018-03-29', 'complete', 75);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (76, 76, null, '2018-04-03', 'complete', 76);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (77, 77, null, '2018-03-24', 'complete', 77);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (78, 78, null, '2018-12-11', 'complete', 78);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (79, 79, null, '2018-06-20', 'in progress', 79);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (80, 80, null, '2018-10-04', 'complete', 80);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (81, 81, null, '2018-10-28', 'in progress', 81);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (82, 82, null, '2018-12-16', 'complete', 82);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (83, 83, null, '2018-11-18', 'in progress', 83);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (84, 84, null, '2017-01-13', 'complete', 84);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (85, 85, null, '2018-08-14', 'complete', 85);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (86, 86, null, '2018-07-19', 'complete', 86);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (87, 87, null, '2018-03-26', 'complete', 87);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (88, 88, null, '2018-04-11', 'complete', 88);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (89, 89, null, '2018-09-20', 'in progress', 89);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (90, 90, null, '2018-04-14', 'complete', 90);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (91, 91, null, '2018-12-02', 'complete', 91);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (92, 92, null, '2018-08-30', 'in progress', 92);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (93, 93, null, '2018-04-10', 'in progress', 93);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (94, 94, null, '2018-04-06', 'complete', 94);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (95, 95, null, '2018-01-06', 'complete', 95);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (96, 96, null, '2018-01-08', 'in progress', 96);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (97, 97, null, '2018-12-05', 'in progress', 97);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (98, 98, null, '2018-05-10', 'in progress', 98);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (99, 99, null, '2018-12-13', 'complete', 99);
insert into application (id, renter_id, requirement, app_submit_date, app_status, unit_id) values (100, 100, null, '2018-05-21', 'complete', 100);