-- insert data into renter table
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (1, 'Stu', 'Deelay', 'Driver License', '07584 Luster Lane');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (2, 'Norean', 'Hosby', 'Driver License', '76158 Eagan Lane');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (3, 'Roberta', 'Aldrin', 'Driver License', '3039 Green Ridge Terrace');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (4, 'Marcia', 'Poat', 'Driver License', '9779 Mitchell Avenue');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (5, 'Maria', 'Klimko', 'Driver License', '721 Farwell Drive');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (6, 'Zorina', 'Birkwood', 'Driver License', '95 Birchwood Parkway');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (7, 'Jack', 'Trail', 'Green Card', '515 Rieder Road');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (8, 'Carry', 'Lamburn', 'Driver License', '246 Loeprich Drive');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (9, 'Dorry', 'Lyttle', 'Passport', '1 Comanche Drive');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (10, 'Geralda', 'Draycott', 'Driver License', '5 Prairie Rose Park');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (11, 'Cordy', 'Seawell', 'Driver License', '96310 Buena Vista Court');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (12, 'Dorise', 'Kaysor', 'Driver License', '523 Talmadge Crossing');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (13, 'Jakie', 'Tees', 'Driver License', '5 Gulseth Place');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (14, 'Elston', 'Feldmus', 'Driver License', '90027 Mallory Terrace');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (15, 'Kenyon', 'Southerden', 'Driver License', '4 Browning Terrace');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (16, 'Chane', 'Spittal', 'Driver License', '37227 Eastwood Parkway');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (17, 'Victoir', 'Purdom', 'Driver License', '73 Rockefeller Parkway');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (18, 'Korey', 'Frango', 'Driver License', '8144 8th Hill');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (19, 'Bradly', 'Arondel', 'Driver License', '02852 East Pass');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (20, 'Nikkie', 'Tembridge', 'Driver License', '921 Monica Circle');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (21, 'Abeu', 'Gravells', 'Passport', '052 Toban Crossing');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (22, 'Conway', 'Cantle', 'Driver License', '0515 Eagan Road');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (23, 'Ryan', 'Sonnenschein', 'Driver License', '54 Merry Circle');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (24, 'Stephannie', 'Magne', 'Driver License', '267 Tomscot Hill');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (25, 'Marguerite', 'Slessor', 'Green Card', '45 Kenwood Drive');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (26, 'Dory', 'Creer', 'Driver License', '6 Ruskin Way');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (27, 'Fredi', 'Schuricht', 'Passport', '4 Tony Trail');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (28, 'Ruperto', 'Lowy', 'Driver License', '3984 Kings Road');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (29, 'Jamie', 'Durtnal', 'Driver License', '105 Declaration Parkway');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (30, 'Phelia', 'Udie', 'Green Card', '37311 Stone Corner Plaza');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (31, 'Valle', 'Wrightson', 'Driver License', '29 Fallview Lane');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (32, 'Gard', 'Rickards', 'Driver License', '5 Waywood Court');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (33, 'Emery', 'Earland', 'Driver License', '6 Main Center');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (34, 'Chicky', 'MacKey', 'Driver License', '2643 Quincy Hill');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (35, 'Kellsie', 'Peto', 'Driver License', '3421 Cambridge Park');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (36, 'Layne', 'Dorrell', 'Driver License', '5840 Fairview Trail');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (37, 'Ivonne', 'Drieu', 'Driver License', '6 Grover Drive');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (38, 'Reuben', 'Doudny', 'Passport', '368 Judy Junction');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (39, 'Jamison', 'Belhomme', 'Driver License', '80 Merrick Street');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (40, 'Gill', 'Havile', 'Green Card', '72737 North Parkway');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (41, 'Arri', 'Drew', 'Driver License', '6 Rockefeller Alley');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (42, 'Violette', 'Isacke', 'Driver License', '66669 Mallard Plaza');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (43, 'Eloise', 'Faughnan', 'Driver License', '6050 Carpenter Lane');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (44, 'Rowena', 'Wynrehame', 'Passport', '2736 Old Gate Drive');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (45, 'Nanice', 'Guitt', 'Driver License', '59 Brown Place');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (46, 'Leighton', 'Mosey', 'Driver License', '036 Donald Point');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (47, 'Elnora', 'Esgate', 'Passport', '7 Granby Plaza');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (48, 'Ree', 'Theseira', 'Driver License', '03709 Melby Lane');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (49, 'Henrietta', 'Float', 'Driver License', '64 Quincy Circle');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (50, 'Kinsley', 'Downie', 'Driver License', '47539 Pepper Wood Court');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (51, 'Van', 'Battison', 'Passport', '4325 Huxley Parkway');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (52, 'Querida', 'Carrett', 'Driver License', '7011 Sauthoff Trail');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (53, 'Collin', 'Killelay', 'Driver License', '163 Vermont Plaza');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (54, 'Dougie', 'Norster', 'Driver License', '5 Portage Crossing');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (55, 'Vernon', 'Swaton', 'Driver License', '4 Golf View Drive');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (56, 'Danyette', 'Edelman', 'Passport', '173 Mallory Junction');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (57, 'Dita', 'MacSwayde', 'Driver License', '9 Del Sol Road');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (58, 'Kelci', 'Bareham', 'Driver License', '6132 Dakota Center');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (59, 'Devina', 'Nowaczyk', 'Driver License', '0 Packers Road');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (60, 'Freida', 'Jutson', 'Green Card', '0 Lukken Center');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (61, 'Guillaume', 'Dreghorn', 'Driver License', '64 Tennyson Plaza');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (62, 'Giselle', 'Kenealy', 'Driver License', '3 Gerald Road');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (63, 'Joice', 'Roffe', 'Driver License', '3 Bashford Parkway');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (64, 'Chadd', 'Vagges', 'Driver License', '66 Kensington Drive');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (65, 'Georgi', 'Skyrme', 'Driver License', '99 Butterfield Circle');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (66, 'Carroll', 'Dalglish', 'Driver License', '95993 Badeau Point');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (67, 'Buffy', 'Winsor', 'Driver License', '0 Macpherson Hill');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (68, 'Othilia', 'McBratney', 'Driver License', '46364 Hauk Plaza');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (69, 'Jeanne', 'Jikovsky', 'Driver License', '478 Hansons Crossing');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (70, 'Imelda', 'Gariff', 'Passport', '1 Sullivan Hill');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (71, 'Joella', 'Danford', 'Driver License', '9848 Mandrake Place');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (72, 'Doyle', 'Stucksbury', 'Driver License', '5555 Summer Ridge Lane');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (73, 'Mallorie', 'Ciani', 'Driver License', '8747 Anderson Point');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (74, 'Elisabet', 'Paulet', 'Green Card', '67797 Cody Crossing');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (75, 'Nappy', 'Loachhead', 'Passport', '71 Riverside Junction');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (76, 'Dael', 'Sleicht', 'Driver License', '24331 Elka Plaza');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (77, 'Shem', 'Drewitt', 'Driver License', '57999 Ridgeway Court');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (78, 'Nettie', 'MacNeil', 'Driver License', '88786 Pawling Court');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (79, 'Randa', 'Shalders', 'Driver License', '4 Forest Dale Park');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (80, 'Mychal', 'Hartfleet', 'Driver License', '5 Raven Pass');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (81, 'Wendie', 'Drugan', 'Driver License', '1 Northwestern Terrace');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (82, 'Lurette', 'Verlinden', 'Driver License', '822 Dixon Way');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (83, 'Orren', 'Rabidge', 'Passport', '1 Sommers Center');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (84, 'Nerty', 'Morrill', 'Driver License', '333 Mariners Cove Junction');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (85, 'Lanny', 'Alywen', 'Driver License', '72 Truax Center');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (86, 'Catie', 'Plaschke', 'Driver License', '6 Sugar Way');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (87, 'Olly', 'Fancutt', 'Driver License', '05532 Esch Junction');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (88, 'Byrle', 'Orto', 'Driver License', '43169 Washington Drive');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (89, 'Philip', 'Batman', 'Driver License', '14 Armistice Lane');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (90, 'Radcliffe', 'Keyte', 'Driver License', '816 Packers Lane');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (91, 'Si', 'Cayle', 'Driver License', '65 Lawn Court');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (92, 'Lannie', 'Sottell', 'Driver License', '56 Ridgeview Alley');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (93, 'Kathy', 'Challice', 'Driver License', '2971 Twin Pines Circle');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (94, 'Georg', 'Witcomb', 'Driver License', '890 High Crossing Alley');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (95, 'Enrique', 'Glazzard', 'Driver License', '6 Fair Oaks Center');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (96, 'Randy', 'Ford', 'Driver License', '58605 Heffernan Avenue');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (97, 'Alanah', 'De Goey', 'Driver License', '6 Walton Center');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (98, 'Francis', 'Lush', 'Driver License', '014 Bartelt Hill');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (99, 'Rinaldo', 'Connar', 'Driver License', '7 Troy Plaza');
insert into renter (id, first_name, last_name, identity_proof, perm_address) values (100, 'Merilyn', 'Golsworthy', 'Driver License', '8530 Thierer Junction');