-- insert data into unit_lease table
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (1,'fixed term',30,260);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (2,'fixed term',30,547);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (3,'fixed term',30,445);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (4,'fixed term',10,745);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (5,'fixed term',20,372);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (6,'fixed term',30,773);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (7,'fixed term',30,417);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (8,'fixed term',40,287);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (9,'monthly',50,741);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (10,'fixed term',20,920);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (11,'fixed term',30,856);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (12,'fixed term',50,810);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (13,'fixed term',20,322);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (14,'fixed term',10,561);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (15,'fixed term',30,478);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (16,'fixed term',50,206);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (17,'fixed term',20,253);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (18,'fixed term',20,444);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (19,'fixed term',50,649);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (20,'fixed term',30,418);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (21,'fixed term',50,541);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (22,'fixed term',30,214);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (23,'fixed term',30,701);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (24,'fixed term',30,679);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (25,'fixed term',10,546);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (26,'fixed term',50,459);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (27,'fixed term',20,681);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (28,'monthly',30,778);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (29,'fixed term',30,217);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (30,'fixed term',40,989);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (31,'fixed term',30,325);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (32,'fixed term',10,699);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (33,'fixed term',30,781);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (34,'monthly',20,259);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (35,'fixed term',20,468);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (36,'fixed term',20,365);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (37,'fixed term',30,951);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (38,'fixed term',20,805);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (39,'monthly',30,294);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (40,'fixed term',10,960);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (41,'fixed term',10,615);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (42,'fixed term',20,470);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (43,'fixed term',10,870);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (44,'monthly',10,351);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (45,'fixed term',20,204);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (46,'fixed term',30,429);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (47,'fixed term',10,849);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (48,'fixed term',10,535);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (49,'fixed term',30,477);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (50,'monthly',30,569);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (51,'fixed term',10,458);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (52,'fixed term',20,382);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (53,'fixed term',20,457);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (54,'monthly',30,373);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (55,'fixed term',20,924);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (56,'monthly',20,402);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (57,'fixed term',20,768);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (58,'fixed term',20,987);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (59,'fixed term',10,571);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (60,'fixed term',20,925);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (61,'monthly',30,345);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (62,'fixed term',30,851);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (63,'fixed term',20,832);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (64,'fixed term',20,561);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (65,'fixed term',10,675);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (66,'monthly',10,942);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (67,'fixed term',30,585);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (68,'monthly',20,714);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (69,'fixed term',50,518);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (70,'fixed term',20,236);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (71,'fixed term',20,272);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (72,'monthly',30,749);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (73,'fixed term',20,504);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (74,'fixed term',30,446);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (75,'fixed term',10,718);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (76,'fixed term',30,609);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (77,'monthly',40,319);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (78,'fixed term',30,570);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (79,'fixed term',40,529);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (80,'fixed term',40,531);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (81,'fixed term',30,742);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (82,'fixed term',30,493);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (83,'fixed term',30,698);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (84,'fixed term',20,875);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (85,'fixed term',20,377);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (86,'fixed term',30,922);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (87,'fixed term',50,221);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (88,'monthly',40,895);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (89,'fixed term',20,614);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (90,'monthly',10,814);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (91,'fixed term',20,562);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (92,'fixed term',20,419);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (93,'fixed term',50,544);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (94,'fixed term',30,973);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (95,'fixed term',20,311);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (96,'fixed term',30,210);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (97,'monthly',30,704);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (98,'fixed term',30,682);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (99,'monthly',40,431);
INSERT INTO `unit_lease` (`id`,`leasing_type`,`app_fee`,`security_deposit`) VALUES (100,'fixed term',10,936);