package GUI;

/**
 *
 * @author Sherry Zhuang
 */

//Imports
import DB.paymentLog;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

//Class to add payment log
public class addPaymentLog extends javax.swing.JFrame
{
    //Create instance
    paymentLog pl = new paymentLog();
    
    //Create form
    public addPaymentLog()
    {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jLabel_LeasingID = new javax.swing.JLabel();
        jLabel_Status = new javax.swing.JLabel();
        jTextField_LeasingID = new javax.swing.JTextField();
        jTextField_Status = new javax.swing.JTextField();
        jButton_Add = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jTextField_Type = new javax.swing.JTextField();
        jTextField_Check = new javax.swing.JTextField();
        jLabel_Type = new javax.swing.JLabel();
        jLabel_PaymentDate = new javax.swing.JLabel();
        jLabel_Check = new javax.swing.JLabel();
        jLabel_Transact = new javax.swing.JLabel();
        jTextField_Transact = new javax.swing.JTextField();
        jDate_PaymentDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel_Title.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel_Title.setText("Add Payment");

        jLabel_LeasingID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LeasingID.setText("Leasing ID");

        jLabel_Status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Status.setText("Payment Status");

        jTextField_LeasingID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_LeasingID.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_LeasingIDKeyTyped(evt);
            }
        });

        jTextField_Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Status.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_StatusKeyTyped(evt);
            }
        });

        jButton_Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_CancelActionPerformed(evt);
            }
        });

        jTextField_Type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Type.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_TypeKeyTyped(evt);
            }
        });

        jTextField_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Check.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_CheckKeyTyped(evt);
            }
        });

        jLabel_Type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Type.setText("Payment Type");

        jLabel_PaymentDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_PaymentDate.setText("Payment Date");

        jLabel_Check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check.setText("Check Number");

        jLabel_Transact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Transact.setText("Transaction");

        jTextField_Transact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Transact.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_TransactKeyTyped(evt);
            }
        });

        jDate_PaymentDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_LeasingID)
                            .addComponent(jLabel_Status)
                            .addComponent(jLabel_PaymentDate)
                            .addComponent(jLabel_Type)
                            .addComponent(jLabel_Check)
                            .addComponent(jLabel_Transact))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Title)
                            .addComponent(jTextField_Status, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jTextField_LeasingID)
                            .addComponent(jTextField_Type, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jTextField_Check, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jTextField_Transact, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jDate_PaymentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jButton_Cancel)
                        .addGap(26, 26, 26)
                        .addComponent(jButton_Add)
                        .addGap(41, 41, 41)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_Title)
                .addGap(34, 34, 34)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LeasingID)
                    .addComponent(jTextField_LeasingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Status)
                    .addComponent(jTextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_PaymentDate)
                    .addComponent(jDate_PaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Type))
                .addGap(29, 29, 29)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Check))
                .addGap(21, 21, 21)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Transact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Transact))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method to verify fields
    public boolean verify()
    {
        if (jTextField_LeasingID.getText().equals("") || jTextField_Status.getText().equals("")
                || jDate_PaymentDate.getDate() == null || jTextField_Type.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or More Empty Field(s).");
            return false;
        } else if (jDate_PaymentDate.getDate().compareTo(new Date()) > 0)
        {
            JOptionPane.showMessageDialog(null, "Invalid Date.");
            return false;
        } else
        {
            return true;
        }
    }
    //Method to add entry
    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_AddActionPerformed
    {//GEN-HEADEREND:event_jButton_AddActionPerformed
        //Get text of fields
        String leasingid = jTextField_LeasingID.getText();
        String status = jTextField_Status.getText();
        String type = jTextField_Type.getText();
        String check = jTextField_Check.getText();
        String transact = jTextField_Transact.getText();
        
        //Verify fields
        if (verify())
        {
            //Convert date
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(jDate_PaymentDate.getDate());
            
            //Insert data
            if ("".equals(check) && "".equals(transact))
            {
                pl.insertUpdateDeletePaymentLog('i', null, leasingid, status, 
                        date, type, null, null);
            } else if (!"".equals(check) && "".equals(transact))
            {
                pl.insertUpdateDeletePaymentLog('i', null, leasingid, status, 
                        date, type, check, null);
            } else if ("".equals(check) && !"".equals(transact))
            {
                pl.insertUpdateDeletePaymentLog('i', null, leasingid, status, 
                        date, type, null, transact);
            } else
            {
                pl.insertUpdateDeletePaymentLog('i', null, leasingid, status, 
                        date, type, check, transact);
            }
            //Set text of fields after add
            jTextField_LeasingID.setText("");
            jTextField_Status.setText("");
            jDate_PaymentDate.setDate(null);
            jTextField_Type.setText("");
            jTextField_Check.setText("");
            jTextField_Transact.setText("");
        }
    }//GEN-LAST:event_jButton_AddActionPerformed

    //Method to cancel
    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_CancelActionPerformed
    {//GEN-HEADEREND:event_jButton_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    //Method to validate and limit field
    private void jTextField_LeasingIDKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_LeasingIDKeyTyped
    {//GEN-HEADEREND:event_jTextField_LeasingIDKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || jTextField_LeasingID.getText().length() > 9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_LeasingIDKeyTyped

    //Method to validate and limit field
    private void jTextField_StatusKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_StatusKeyTyped
    {//GEN-HEADEREND:event_jTextField_StatusKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || jTextField_Status.getText().length() > 9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_StatusKeyTyped

    //Method to validate and limit field
    private void jTextField_TypeKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_TypeKeyTyped
    {//GEN-HEADEREND:event_jTextField_TypeKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || jTextField_Type.getText().length() > 19)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_TypeKeyTyped

    //Method to validate and limit field
    private void jTextField_CheckKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_CheckKeyTyped
    {//GEN-HEADEREND:event_jTextField_CheckKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || jTextField_Check.getText().length() > 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_CheckKeyTyped

    //Method to validate and limit field
    private void jTextField_TransactKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_TransactKeyTyped
    {//GEN-HEADEREND:event_jTextField_TransactKeyTyped
        if (!Character.isDigit(evt.getKeyChar())|| jTextField_Transact.getText().length() > 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_TransactKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(addPaymentLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(addPaymentLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(addPaymentLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(addPaymentLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new addPaymentLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Cancel;
    private com.toedter.calendar.JDateChooser jDate_PaymentDate;
    private javax.swing.JLabel jLabel_Check;
    private javax.swing.JLabel jLabel_LeasingID;
    private javax.swing.JLabel jLabel_PaymentDate;
    private javax.swing.JLabel jLabel_Status;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_Transact;
    private javax.swing.JLabel jLabel_Type;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField jTextField_Check;
    private javax.swing.JTextField jTextField_LeasingID;
    private javax.swing.JTextField jTextField_Status;
    private javax.swing.JTextField jTextField_Transact;
    private javax.swing.JTextField jTextField_Type;
    // End of variables declaration//GEN-END:variables
} //End addPaymentLog
