package GUI;

/**
 *
 * @author Sherry Zhuang
 */

//Imports
import DB.property;
import javax.swing.JOptionPane;

//Class to add property
public class addProperty extends javax.swing.JFrame
{
    //Create instance
    property p = new property();
    
    //Create form
    public addProperty()
    {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jLabel_St = new javax.swing.JLabel();
        jLabel_City = new javax.swing.JLabel();
        jTextField_St = new javax.swing.JTextField();
        jTextField_City = new javax.swing.JTextField();
        jButton_Add = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jTextField_Country = new javax.swing.JTextField();
        jTextField_ZIP = new javax.swing.JTextField();
        jTextField_State = new javax.swing.JTextField();
        jLabel_Country = new javax.swing.JLabel();
        jLabel_State = new javax.swing.JLabel();
        jLabel_ZIP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel_Title.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel_Title.setText("Add Property");

        jLabel_St.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_St.setText("Street");

        jLabel_City.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_City.setText("City");

        jTextField_St.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_St.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_StKeyTyped(evt);
            }
        });

        jTextField_City.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_City.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_CityKeyTyped(evt);
            }
        });

        jButton_Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_CancelActionPerformed(evt);
            }
        });

        jTextField_Country.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Country.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_CountryKeyTyped(evt);
            }
        });

        jTextField_ZIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_ZIP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_ZIPKeyTyped(evt);
            }
        });

        jTextField_State.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_State.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_StateKeyTyped(evt);
            }
        });

        jLabel_Country.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Country.setText("Country");

        jLabel_State.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_State.setText("State");

        jLabel_ZIP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_ZIP.setText("ZIP");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_St)
                            .addComponent(jLabel_City)
                            .addComponent(jLabel_State)
                            .addComponent(jLabel_Country)
                            .addComponent(jLabel_ZIP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Title)
                            .addComponent(jTextField_City, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jTextField_St)
                            .addComponent(jTextField_Country, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jTextField_ZIP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jTextField_State, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton_Cancel)
                        .addGap(27, 27, 27)
                        .addComponent(jButton_Add)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_Title)
                .addGap(34, 34, 34)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_St)
                    .addComponent(jTextField_St, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_City)
                    .addComponent(jTextField_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_State))
                .addGap(27, 27, 27)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Country))
                .addGap(29, 29, 29)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ZIP))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method to verify fields
    public boolean verify()
    {
        if (jTextField_St.getText().equals("") || jTextField_City.getText().equals("")
                || jTextField_State.getText().equals("") || jTextField_Country.getText().equals("")
                || jTextField_ZIP.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or More Empty Field(s).");
            return false;
        } else
        {
            return true;
        }
    }
    //Method to add entry
    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_AddActionPerformed
    {//GEN-HEADEREND:event_jButton_AddActionPerformed
        //Get text of fields
        String st = jTextField_St.getText();
        String city = jTextField_City.getText();
        String state = jTextField_State.getText();
        String country = jTextField_Country.getText();
        String zip = jTextField_ZIP.getText();
        
        //Verify fields
        if (verify())
        {
            //Insert data
            p.insertUpdateDeleteProperty('i', null, st, city, state, country, zip);
            //Set text of fields after add
            jTextField_St.setText("");
            jTextField_City.setText("");
            jTextField_State.setText("");
            jTextField_Country.setText("");
            jTextField_ZIP.setText("");
        }
    }//GEN-LAST:event_jButton_AddActionPerformed

    //Method to cancel
    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_CancelActionPerformed
    {//GEN-HEADEREND:event_jButton_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    //Method to limit field
    private void jTextField_StKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_StKeyTyped
    {//GEN-HEADEREND:event_jTextField_StKeyTyped
        if (jTextField_St.getText().length() > 98)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_StKeyTyped

    //Method to validate and limit field
    private void jTextField_CityKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_CityKeyTyped
    {//GEN-HEADEREND:event_jTextField_CityKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || jTextField_City.getText().length() > 48)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_CityKeyTyped

    //Method to validate and limit field
    private void jTextField_StateKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_StateKeyTyped
    {//GEN-HEADEREND:event_jTextField_StateKeyTyped
        if (Character.isDigit(evt.getKeyChar())|| jTextField_State.getText().length() > 18)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_StateKeyTyped

    //Method to validate and limit field
    private void jTextField_CountryKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_CountryKeyTyped
    {//GEN-HEADEREND:event_jTextField_CountryKeyTyped
        if (Character.isDigit(evt.getKeyChar())|| jTextField_Country.getText().length() > 18)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_CountryKeyTyped

    //Method to validate and limit field
    private void jTextField_ZIPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_ZIPKeyTyped
    {//GEN-HEADEREND:event_jTextField_ZIPKeyTyped
        if (!Character.isDigit(evt.getKeyChar())|| jTextField_ZIP.getText().length() > 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_ZIPKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(addProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(addProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(addProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(addProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new addProperty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JLabel jLabel_City;
    private javax.swing.JLabel jLabel_Country;
    private javax.swing.JLabel jLabel_St;
    private javax.swing.JLabel jLabel_State;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_ZIP;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField jTextField_City;
    private javax.swing.JTextField jTextField_Country;
    private javax.swing.JTextField jTextField_St;
    private javax.swing.JTextField jTextField_State;
    private javax.swing.JTextField jTextField_ZIP;
    // End of variables declaration//GEN-END:variables
} //End addProperty