package GUI;
/**
 *
 * @author Sherry Zhuang
 */

//Imports
import DB.renter;
import javax.swing.JOptionPane;

//Class to add renter
public class addRenter extends javax.swing.JFrame
{
    //Create instance
    renter r = new renter();
    
    //Create form
    public addRenter()
    {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jLabel_FName = new javax.swing.JLabel();
        jLabel_LName = new javax.swing.JLabel();
        jLabel_IDProof = new javax.swing.JLabel();
        jLabel_Address = new javax.swing.JLabel();
        jTextField_FName = new javax.swing.JTextField();
        jTextField_LName = new javax.swing.JTextField();
        jTextField_IDProof = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jButton_Add = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel_Title.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel_Title.setText("Add Renter");

        jLabel_FName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_FName.setText("First Name");

        jLabel_LName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LName.setText("Last Name");

        jLabel_IDProof.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_IDProof.setText("Identity Proof");

        jLabel_Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Address.setText("Address");

        jTextField_FName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_FName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_FNameKeyTyped(evt);
            }
        });

        jTextField_LName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_LName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_LNameKeyTyped(evt);
            }
        });

        jTextField_IDProof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_IDProof.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_IDProofKeyTyped(evt);
            }
        });

        jTextArea_Address.setColumns(20);
        jTextArea_Address.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea_Address.setRows(5);
        jTextArea_Address.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextArea_AddressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_Address);

        jButton_Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_FName)
                            .addComponent(jLabel_LName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Title)
                            .addComponent(jTextField_LName, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jTextField_FName)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_IDProof)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel_Address)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField_IDProof, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jButton_Cancel)
                                .addGap(26, 26, 26)
                                .addComponent(jButton_Add)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_Title)
                .addGap(34, 34, 34)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FName)
                    .addComponent(jTextField_FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LName)
                    .addComponent(jTextField_LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IDProof)
                    .addComponent(jTextField_IDProof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Address)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Method to verify fields
    public boolean verify()
    {

        if (jTextField_FName.getText().equals("") || jTextField_LName.getText().equals("")
                || jTextField_IDProof.getText().equals("") || jTextArea_Address.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or More Empty Field(s).");
            return false;
        } else
        {
            return true;
        }

    }
    //Method to add entry
    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_AddActionPerformed
    {//GEN-HEADEREND:event_jButton_AddActionPerformed
        //Get text of fields
        String fname = jTextField_FName.getText();
        String lname = jTextField_LName.getText();
        String idproof = jTextField_IDProof.getText();
        String address = jTextArea_Address.getText();

        //Verify fields
        if (verify())
        {
            //Insert data
            r.insertUpdateDeleteRenter('i', null, fname, lname, idproof, address);
            //Set text of fields after add
            jTextField_FName.setText("");
            jTextField_LName.setText("");
            jTextField_IDProof.setText("");
            jTextArea_Address.setText("");
        }
    }//GEN-LAST:event_jButton_AddActionPerformed

    //Method to cancel
    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_CancelActionPerformed
    {//GEN-HEADEREND:event_jButton_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    //Method to validate and limit field
    private void jTextField_FNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_FNameKeyTyped
    {//GEN-HEADEREND:event_jTextField_FNameKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || jTextField_FName.getText().length() > 48)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_FNameKeyTyped

    //Method to validate and limit field
    private void jTextField_LNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_LNameKeyTyped
    {//GEN-HEADEREND:event_jTextField_LNameKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || jTextField_LName.getText().length() > 48)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_LNameKeyTyped

    //Method to validate and limit field
    private void jTextField_IDProofKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_IDProofKeyTyped
    {//GEN-HEADEREND:event_jTextField_IDProofKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || jTextField_IDProof.getText().length() > 48)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_IDProofKeyTyped

    //Method to limit field
    private void jTextArea_AddressKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextArea_AddressKeyTyped
    {//GEN-HEADEREND:event_jTextArea_AddressKeyTyped
        if (jTextArea_Address.getText().length() > 98)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextArea_AddressKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(addRenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(addRenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(addRenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(addRenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new addRenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JLabel jLabel_Address;
    private javax.swing.JLabel jLabel_FName;
    private javax.swing.JLabel jLabel_IDProof;
    private javax.swing.JLabel jLabel_LName;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Address;
    private javax.swing.JTextField jTextField_FName;
    private javax.swing.JTextField jTextField_IDProof;
    private javax.swing.JTextField jTextField_LName;
    // End of variables declaration//GEN-END:variables
} //End addRenter