package GUI;

/**
 *
 * @author Sherry Zhuang
 */

//Imports
import DB.connectDB;
import DB.connectReport;
import java.io.File;
import java.util.Map;
import java.util.HashMap;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.JasperFillManager;

//Class to display home menu
public class homeMenu extends javax.swing.JFrame
{
    //Default paths of reports for viewing
    static final File DAILYREPORT = new File("Reports/getDailyReport.jasper");
    static final File WEEKLYREPORT = new File("Reports/getWeeklyReport.jasper");
    static final File MONTHLYREPORT = new File("Reports/getMonthlyReport.jasper");
    static final File YEARLYREPORT = new File("Reports/getYearlyReport.jasper");

    //Default paths of reports for pdf conversion
    static final String DAILY_REPORT = "Reports/getDailyReport.jrxml";
    static final String MONTHLY_REPORT = "Reports/getMonthlyReport.jrxml";
    static final String WEEKLY_REPORT = "Reports/getWeeklyReport.jrxml";
    static final String YEARLY_REPORT = "Reports/getYearlyReport.jrxml";

    //Create instance
    connectReport cR = new connectReport();

    //Create form
    public homeMenu()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Logo = new javax.swing.JLabel();
        jLabel_Greeting = new javax.swing.JLabel();
        jLabel_LUXY = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Properties = new javax.swing.JMenu();
        addProperty = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        manageProperty = new javax.swing.JMenuItem();
        jMenu_PaymentLogs = new javax.swing.JMenu();
        addPaymentLog = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        managePaymentLog = new javax.swing.JMenuItem();
        jMenu_Renters = new javax.swing.JMenu();
        addRenter = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        manageRenter = new javax.swing.JMenuItem();
        jMenu_ViewReports = new javax.swing.JMenu();
        dailyReport = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        weeklyReport = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        monthlyReport = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        yearlyReport = new javax.swing.JMenuItem();
        jMenu_ViewReports1 = new javax.swing.JMenu();
        dailyReportExport = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        weeklyReportExport = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        monthlyReportExport = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        yearlyReportExport = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel_Logo)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Logo)
                .addContainerGap())
        );

        jLabel_Greeting.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        jLabel_Greeting.setForeground(new java.awt.Color(0, 0, 102));
        jLabel_Greeting.setText("Welcome User");

        jLabel_LUXY.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        jLabel_LUXY.setForeground(new java.awt.Color(0, 0, 102));
        jLabel_LUXY.setText("L◆U◆X◆Y");

        jMenu_Properties.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_Properties.setText(" Properties ");
        jMenu_Properties.setBorderPainted(true);
        jMenu_Properties.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        addProperty.setText("Add");
        addProperty.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addPropertyActionPerformed(evt);
            }
        });
        jMenu_Properties.add(addProperty);
        jMenu_Properties.add(jSeparator1);

        manageProperty.setText("Manage");
        manageProperty.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                managePropertyActionPerformed(evt);
            }
        });
        jMenu_Properties.add(manageProperty);

        jMenuBar1.add(jMenu_Properties);

        jMenu_PaymentLogs.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_PaymentLogs.setText(" Payment Logs ");
        jMenu_PaymentLogs.setBorderPainted(true);
        jMenu_PaymentLogs.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        addPaymentLog.setText("Add");
        addPaymentLog.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addPaymentLogActionPerformed(evt);
            }
        });
        jMenu_PaymentLogs.add(addPaymentLog);
        jMenu_PaymentLogs.add(jSeparator2);

        managePaymentLog.setText("Manage");
        managePaymentLog.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                managePaymentLogActionPerformed(evt);
            }
        });
        jMenu_PaymentLogs.add(managePaymentLog);

        jMenuBar1.add(jMenu_PaymentLogs);

        jMenu_Renters.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_Renters.setText(" Renters ");
        jMenu_Renters.setBorderPainted(true);
        jMenu_Renters.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        addRenter.setText("Add");
        addRenter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addRenterActionPerformed(evt);
            }
        });
        jMenu_Renters.add(addRenter);
        jMenu_Renters.add(jSeparator4);

        manageRenter.setText("Manage");
        manageRenter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                manageRenterActionPerformed(evt);
            }
        });
        jMenu_Renters.add(manageRenter);

        jMenuBar1.add(jMenu_Renters);

        jMenu_ViewReports.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_ViewReports.setText(" View Reports ");
        jMenu_ViewReports.setBorderPainted(true);
        jMenu_ViewReports.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        dailyReport.setText("Daily");
        dailyReport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dailyReportActionPerformed(evt);
            }
        });
        jMenu_ViewReports.add(dailyReport);
        jMenu_ViewReports.add(jSeparator3);

        weeklyReport.setText("Weekly");
        weeklyReport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                weeklyReportActionPerformed(evt);
            }
        });
        jMenu_ViewReports.add(weeklyReport);
        jMenu_ViewReports.add(jSeparator6);

        monthlyReport.setText("Monthly");
        monthlyReport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                monthlyReportActionPerformed(evt);
            }
        });
        jMenu_ViewReports.add(monthlyReport);
        jMenu_ViewReports.add(jSeparator7);

        yearlyReport.setText("Yearly");
        yearlyReport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yearlyReportActionPerformed(evt);
            }
        });
        jMenu_ViewReports.add(yearlyReport);

        jMenuBar1.add(jMenu_ViewReports);

        jMenu_ViewReports1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_ViewReports1.setText("Quick Export");
        jMenu_ViewReports1.setBorderPainted(true);
        jMenu_ViewReports1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        dailyReportExport.setText("Daily");
        dailyReportExport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dailyReportExportActionPerformed(evt);
            }
        });
        jMenu_ViewReports1.add(dailyReportExport);
        jMenu_ViewReports1.add(jSeparator5);

        weeklyReportExport.setText("Weekly");
        weeklyReportExport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                weeklyReportExportActionPerformed(evt);
            }
        });
        jMenu_ViewReports1.add(weeklyReportExport);
        jMenu_ViewReports1.add(jSeparator8);

        monthlyReportExport.setText("Monthly");
        monthlyReportExport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                monthlyReportExportActionPerformed(evt);
            }
        });
        jMenu_ViewReports1.add(monthlyReportExport);
        jMenu_ViewReports1.add(jSeparator9);

        yearlyReportExport.setText("Yearly");
        yearlyReportExport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yearlyReportExportActionPerformed(evt);
            }
        });
        jMenu_ViewReports1.add(yearlyReportExport);

        jMenuBar1.add(jMenu_ViewReports1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Greeting, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_LUXY)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel_Greeting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_LUXY)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method to add property
    private void addPropertyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addPropertyActionPerformed
    {//GEN-HEADEREND:event_addPropertyActionPerformed
        //Create instance
        addProperty addP = new addProperty();
        addP.pack();
        addP.setVisible(true);
        addP.setLocationRelativeTo(null);
        addP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addPropertyActionPerformed
    //Method to manage property
    private void managePropertyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_managePropertyActionPerformed
    {//GEN-HEADEREND:event_managePropertyActionPerformed
        //Create instance
        manageProperty mngP = new manageProperty();
        mngP.pack();
        mngP.setVisible(true);
        mngP.setLocationRelativeTo(null);
        mngP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_managePropertyActionPerformed
    //Method to add payment log
    private void addPaymentLogActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addPaymentLogActionPerformed
    {//GEN-HEADEREND:event_addPaymentLogActionPerformed
        //Create instance
        addPaymentLog addPL = new addPaymentLog();
        addPL.pack();
        addPL.setVisible(true);
        addPL.setLocationRelativeTo(null);
        addPL.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addPaymentLogActionPerformed
    //Method to manage payment log
    private void managePaymentLogActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_managePaymentLogActionPerformed
    {//GEN-HEADEREND:event_managePaymentLogActionPerformed
        //Create instance
        managePaymentLog mngPL = new managePaymentLog();
        mngPL.pack();
        mngPL.setVisible(true);
        mngPL.setLocationRelativeTo(null);
        mngPL.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_managePaymentLogActionPerformed
    //Method to add renter
    private void addRenterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addRenterActionPerformed
    {//GEN-HEADEREND:event_addRenterActionPerformed
        //Create instance
        addRenter addR = new addRenter();
        addR.pack();
        addR.setVisible(true);
        addR.setLocationRelativeTo(null);
        addR.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addRenterActionPerformed
    //Method to manage renter
    private void manageRenterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_manageRenterActionPerformed
    {//GEN-HEADEREND:event_manageRenterActionPerformed
        //Create instance
        manageRenter mngR = new manageRenter();
        mngR.pack();
        mngR.setVisible(true);
        mngR.setLocationRelativeTo(null);
        mngR.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_manageRenterActionPerformed
    //View daily report
    private void dailyReportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dailyReportActionPerformed
    {//GEN-HEADEREND:event_dailyReportActionPerformed
        try (Connection con = connectDB.getConnection())
        {
            //View jasper report
            Map parameters = new HashMap();
            JasperReport report = (JasperReport) JRLoader.loadObject(DAILYREPORT);
            JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
            JFrame frame = new JFrame("Daily Report");
            frame.setVisible(true);
            frame.setSize(new Dimension(1200, 1000));
            frame.getContentPane().add(new JRViewer(jasperPrint));
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } //Handle errors
        catch (JRException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.toString());
        }
    }//GEN-LAST:event_dailyReportActionPerformed
    //View weekly report
    private void weeklyReportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_weeklyReportActionPerformed
    {//GEN-HEADEREND:event_weeklyReportActionPerformed
        try (Connection con = connectDB.getConnection())
        {
            //View jasper report
            Map parameters = new HashMap();
            JasperReport report = (JasperReport) JRLoader.loadObject(WEEKLYREPORT);
            JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
            JFrame frame = new JFrame("Weekly Report");
            frame.setVisible(true);
            frame.setSize(new Dimension(1200, 1000));
            frame.getContentPane().add(new JRViewer(jasperPrint));
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } //Handle errors
        catch (JRException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.toString());
        }
    }//GEN-LAST:event_weeklyReportActionPerformed
    //View monthly report
    private void monthlyReportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_monthlyReportActionPerformed
    {//GEN-HEADEREND:event_monthlyReportActionPerformed
        try (Connection con = connectDB.getConnection())
        {
            //View jasper report
            Map parameters = new HashMap();
            JasperReport report = (JasperReport) JRLoader.loadObject(MONTHLYREPORT);
            JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
            JFrame frame = new JFrame("Monthly Report");
            frame.setVisible(true);
            frame.setSize(new Dimension(1200, 1000));
            frame.getContentPane().add(new JRViewer(jasperPrint));
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } //Handle errors
        catch (JRException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.toString());
        }
    }//GEN-LAST:event_monthlyReportActionPerformed
    //View yearly report
    private void yearlyReportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yearlyReportActionPerformed
    {//GEN-HEADEREND:event_yearlyReportActionPerformed
        try (Connection con = connectDB.getConnection())
        {
            //View jasper report
            Map parameters = new HashMap();
            JasperReport report = (JasperReport) JRLoader.loadObject(YEARLYREPORT);
            JasperPrint jasperPrint = JasperFillManager.fillReport(report, parameters, con);
            JFrame frame = new JFrame("Yearly Report");
            frame.setVisible(true);
            frame.setSize(new Dimension(1200, 1000));
            frame.getContentPane().add(new JRViewer(jasperPrint));
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } //Handle errors
        catch (JRException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.toString());
        }

    }//GEN-LAST:event_yearlyReportActionPerformed
    //Method to quick export daily report
    private void dailyReportExportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dailyReportExportActionPerformed
    {//GEN-HEADEREND:event_dailyReportExportActionPerformed
        //Export report to PDF
        try
        {
            cR.exportReport(DAILY_REPORT, "Daily");
            JOptionPane.showMessageDialog(null, "SUCCESS: Report saved as PDF.");
        } //Handle errors
        catch (JRException | SQLException | ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.toString());
        }
    }//GEN-LAST:event_dailyReportExportActionPerformed
    //Method to quick export weekly report
    private void weeklyReportExportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_weeklyReportExportActionPerformed
    {//GEN-HEADEREND:event_weeklyReportExportActionPerformed
        //Export report to PDF
        try
        {
            cR.exportReport(WEEKLY_REPORT, "Weekly");
            JOptionPane.showMessageDialog(null, "SUCCESS: Report saved as PDF.");
        } //Handle errors
        catch (JRException | SQLException | ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.toString());
        }
    }//GEN-LAST:event_weeklyReportExportActionPerformed
    //Method to quick export monthly report
    private void monthlyReportExportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_monthlyReportExportActionPerformed
    {//GEN-HEADEREND:event_monthlyReportExportActionPerformed
        //Export report to PDF
        try
        {
            cR.exportReport(MONTHLY_REPORT, "Monthly");
            JOptionPane.showMessageDialog(null, "SUCCESS: Report saved as PDF.");
        } //Handle errors
        catch (JRException | SQLException | ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.toString());
        }
    }//GEN-LAST:event_monthlyReportExportActionPerformed
    //Method to quick export yearly report
    private void yearlyReportExportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yearlyReportExportActionPerformed
    {//GEN-HEADEREND:event_yearlyReportExportActionPerformed
        //Export report to PDF
        try
        {
            cR.exportReport(YEARLY_REPORT, "Yearly");
            JOptionPane.showMessageDialog(null, "SUCCESS: Report saved as PDF.");
        } //Handle errors
        catch (JRException | SQLException | ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.toString());
        }
    }//GEN-LAST:event_yearlyReportExportActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(homeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(homeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(homeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(homeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new homeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addPaymentLog;
    private javax.swing.JMenuItem addProperty;
    private javax.swing.JMenuItem addRenter;
    private javax.swing.JMenuItem dailyReport;
    private javax.swing.JMenuItem dailyReportExport;
    public static javax.swing.JLabel jLabel_Greeting;
    private javax.swing.JLabel jLabel_LUXY;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_PaymentLogs;
    private javax.swing.JMenu jMenu_Properties;
    private javax.swing.JMenu jMenu_Renters;
    private javax.swing.JMenu jMenu_ViewReports;
    private javax.swing.JMenu jMenu_ViewReports1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem managePaymentLog;
    private javax.swing.JMenuItem manageProperty;
    private javax.swing.JMenuItem manageRenter;
    private javax.swing.JMenuItem monthlyReport;
    private javax.swing.JMenuItem monthlyReportExport;
    private javax.swing.JMenuItem weeklyReport;
    private javax.swing.JMenuItem weeklyReportExport;
    private javax.swing.JMenuItem yearlyReport;
    private javax.swing.JMenuItem yearlyReportExport;
    // End of variables declaration//GEN-END:variables
} //End homeMenu
