package GUI;

/**
 *
 * @author Sherry Zhuang
 */

//Imports
import DB.paymentLog;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.sun.glass.events.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

//Class to display manage payment log page
public class managePaymentLog extends javax.swing.JFrame
{
    //Create instance
    paymentLog pl = new paymentLog();
    DefaultTableModel model;
    int rowIndex;
    
    //Create form
    public managePaymentLog()
    {
        initComponents();
        //Fill table
        pl.fillPaymentLogJtable(jTable, "");
        //Set model
        model = (DefaultTableModel) jTable.getModel();
        //Set table attributes
        jTable.setRowHeight(30);
        jTable.setShowGrid(true);
        jTable.setGridColor(Color.blue);
        jTable.setSelectionBackground(Color.BLACK);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jLabel_LeasingID = new javax.swing.JLabel();
        jLabel_Status = new javax.swing.JLabel();
        jLabel_PaymentDate = new javax.swing.JLabel();
        jLabel_Check = new javax.swing.JLabel();
        jTextField_LeasingID = new javax.swing.JTextField();
        jTextField_Status = new javax.swing.JTextField();
        jButton_Edit = new javax.swing.JButton();
        jButton_Remove = new javax.swing.JButton();
        jLabel_Search = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel_ID = new javax.swing.JLabel();
        jTextField_Type = new javax.swing.JTextField();
        jLabelPayment_Type = new javax.swing.JLabel();
        jTextField_Check = new javax.swing.JTextField();
        jLabel_Transact = new javax.swing.JLabel();
        jTextField_Transact = new javax.swing.JTextField();
        jDate_PaymentDate = new com.toedter.calendar.JDateChooser();
        jTextField_Search = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel_Title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_Title.setText("Manage Payment Log");

        jLabel_LeasingID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LeasingID.setText("Leasing ID");

        jLabel_Status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Status.setText("Payment Status");

        jLabel_PaymentDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_PaymentDate.setText("Payment Date");

        jLabel_Check.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Check.setText("Check Number");

        jTextField_LeasingID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_LeasingID.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_LeasingIDKeyTyped(evt);
            }
        });

        jTextField_Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Status.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_StatusKeyTyped(evt);
            }
        });

        jButton_Edit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Remove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Remove.setText("Remove");
        jButton_Remove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_RemoveActionPerformed(evt);
            }
        });

        jLabel_Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Search.setText("Search");

        jTextField_ID.setEditable(false);
        jTextField_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel_ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_ID.setText("ID");

        jTextField_Type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Type.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_TypeKeyTyped(evt);
            }
        });

        jLabelPayment_Type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPayment_Type.setText("Payment Type");

        jTextField_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Check.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_CheckKeyTyped(evt);
            }
        });

        jLabel_Transact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Transact.setText("Transaction");

        jTextField_Transact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Transact.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_TransactKeyTyped(evt);
            }
        });

        jDate_PaymentDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField_Search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Search.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTextField_SearchKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setToolTipText("");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "Leasing ID", "Status", "Date", "Type", "Check Num", "Transaction"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTableMouseClicked(evt);
            }
        });
        jTable.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTableKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0)
        {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(45);
            jTable.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable.getColumnModel().getColumn(2).setPreferredWidth(45);
            jTable.getColumnModel().getColumn(3).setPreferredWidth(95);
            jTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel_Title))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel_Transact)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_Transact, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel_Check)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                        .addComponent(jLabelPayment_Type)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jButton_Remove)
                                .addGap(30, 30, 30)
                                .addComponent(jButton_Edit))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel_Status)
                                            .addComponent(jLabel_LeasingID)
                                            .addComponent(jLabel_PaymentDate))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextField_LeasingID, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jDate_PaymentDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel_Search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_LeasingID)
                            .addComponent(jTextField_LeasingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Status)
                            .addComponent(jTextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDate_PaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_PaymentDate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPayment_Type)
                            .addComponent(jTextField_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Check)
                            .addComponent(jTextField_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Transact)
                            .addComponent(jTextField_Transact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Search)
                            .addComponent(jLabel_ID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Method to verify fields
    public boolean verify()
    {
        if (jTextField_LeasingID.getText().equals("")
                || jTextField_Status.getText().equals("")
                || jDate_PaymentDate.getDate() == null
                || jTextField_Type.getText().equals("")
                || jTextField_ID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or More Empty Field(s).");
            return false;
        } else if (jDate_PaymentDate.getDate().compareTo(new Date()) > 0)
        {
            JOptionPane.showMessageDialog(null, "Invalid date.");
            return false;
        } else
        {
            return true;
        }
    }
    //Method to remove entry
    private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_RemoveActionPerformed
    {//GEN-HEADEREND:event_jButton_RemoveActionPerformed
        //Verify selection
        if (jTextField_ID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No Payment Log Selected.");
        } else
        {
            int id = Integer.valueOf(jTextField_ID.getText());
            //Delete data
            pl.insertUpdateDeletePaymentLog('d', id, null, null, null, null, null,
                    null);
            pl.fillPaymentLogJtable(jTable, "");
            
            //Refresh table
            jTable.setModel(new DefaultTableModel(null, new Object[]
            {
                "ID", "Leasing ID", "Status", "Date", "Type", "Check Num",
                "Transaction"
            }));
            pl.fillPaymentLogJtable(jTable, jTextField_Search.getText());
            
            //Set text of fields after delete
            jTextField_ID.setText("");
            jTextField_LeasingID.setText("");
            jTextField_Status.setText("");
            jDate_PaymentDate.setDate(null);
            jTextField_Type.setText("");
            jTextField_Check.setText("");
            jTextField_Transact.setText("");
            jTextField_Search.setText("");
        }
    }//GEN-LAST:event_jButton_RemoveActionPerformed
    //Method to edit entry
    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_EditActionPerformed
    {//GEN-HEADEREND:event_jButton_EditActionPerformed
        //Get text of fields
        String leasingid = jTextField_LeasingID.getText();
        String status = jTextField_Status.getText();
        String type = jTextField_Type.getText();
        String check = jTextField_Check.getText();
        String transact = jTextField_Transact.getText();
        int id = Integer.valueOf(jTextField_ID.getText());
        
        //Verify selection
        if (verify())
        {
            //Convert date
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(jDate_PaymentDate.getDate());
            
            //Update data
            if ("".equals(check) && "".equals(transact))
            {
                pl.insertUpdateDeletePaymentLog('u', id, leasingid, status, date,
                        type, null, null);
            } else if (!"".equals(check) && "".equals(transact))
            {
                pl.insertUpdateDeletePaymentLog('u', id, leasingid, status, date,
                        type, check, null);
            } else if ("".equals(check) && !"".equals(transact))
            {
                pl.insertUpdateDeletePaymentLog('u', id, leasingid, status, date,
                        type, null, transact);
            } else
            {
                pl.insertUpdateDeletePaymentLog('u', id, leasingid, status, date,
                        type, check, transact);
            }
            
            //Set text of fields after update
            jTextField_ID.setText("");
            jTextField_LeasingID.setText("");
            jTextField_Status.setText("");
            jDate_PaymentDate.setDate(null);
            jTextField_Type.setText("");
            jTextField_Check.setText("");
            jTextField_Transact.setText("");
            jTextField_Search.setText("");

            //Refresh table
            jTable.setModel(new DefaultTableModel(null, new Object[]
            {
                "ID", "Leasing ID", "Status", "Date", "Type", "Check Num",
                "Transaction"
            }));
            pl.fillPaymentLogJtable(jTable, "");
        }
    }//GEN-LAST:event_jButton_EditActionPerformed
    //Method to validate and limit field
    private void jTextField_LeasingIDKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_LeasingIDKeyTyped
    {//GEN-HEADEREND:event_jTextField_LeasingIDKeyTyped
        if (!Character.isDigit(evt.getKeyChar())
                || jTextField_LeasingID.getText().length() > 9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_LeasingIDKeyTyped
    //Method to validate and limit field
    private void jTextField_StatusKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_StatusKeyTyped
    {//GEN-HEADEREND:event_jTextField_StatusKeyTyped
        if (Character.isDigit(evt.getKeyChar())
                || jTextField_Status.getText().length() > 9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_StatusKeyTyped
    //Method to validate and limit field
    private void jTextField_TypeKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_TypeKeyTyped
    {//GEN-HEADEREND:event_jTextField_TypeKeyTyped
        if (Character.isDigit(evt.getKeyChar())
                || jTextField_Type.getText().length() > 19)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_TypeKeyTyped
    //Method to validate and limit field
    private void jTextField_CheckKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_CheckKeyTyped
    {//GEN-HEADEREND:event_jTextField_CheckKeyTyped
        if (!Character.isDigit(evt.getKeyChar())
                || jTextField_Check.getText().length() > 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_CheckKeyTyped
    //Method to validate and limit field
    private void jTextField_TransactKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_TransactKeyTyped
    {//GEN-HEADEREND:event_jTextField_TransactKeyTyped
        if (!Character.isDigit(evt.getKeyChar())
                || jTextField_Transact.getText().length() > 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_TransactKeyTyped
    //Method to fill fields if entry clicked
    private void jTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableMouseClicked
    {//GEN-HEADEREND:event_jTableMouseClicked
        model = (DefaultTableModel) jTable.getModel();
        rowIndex = jTable.getSelectedRow();
        //Get info of entry
        jTextField_ID.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField_LeasingID.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField_Status.setText(model.getValueAt(rowIndex, 2).toString());
        jTextField_Type.setText(model.getValueAt(rowIndex, 4).toString());
        
        //Convert date
        Date bdate;
        try
        {
            bdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex,
                    3).toString());
            jDate_PaymentDate.setDate(bdate);
          //Handle errors
        } catch (ParseException ex)
        {
            Logger.getLogger(managePaymentLog.class.getName()).log(Level.SEVERE,
                    null, ex);
        }
        if ("null".equals(String.valueOf(model.getValueAt(rowIndex, 5)))
                && "null".equals(String.valueOf(model.getValueAt(rowIndex, 6))))
        {
            jTextField_Check.setText("");
            jTextField_Transact.setText("");
        } else if (!"null".equals(String.valueOf(model.getValueAt(rowIndex, 5)))
                && "null".equals(String.valueOf(model.getValueAt(rowIndex, 6))))
        {
            jTextField_Check.setText(model.getValueAt(rowIndex, 5).toString());
            jTextField_Transact.setText("");
        } else if ("null".equals(String.valueOf(model.getValueAt(rowIndex, 5)))
                && !"null".equals(String.valueOf(model.getValueAt(rowIndex, 6))))
        {
            jTextField_Check.setText("");
            jTextField_Transact.setText(model.getValueAt(rowIndex, 6).toString());
        } else
        {
            jTextField_Check.setText(model.getValueAt(rowIndex, 5).toString());
            jTextField_Transact.setText(model.getValueAt(rowIndex, 6).toString());
        }
    }//GEN-LAST:event_jTableMouseClicked

   //Method to search
    private void jTextField_SearchKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_SearchKeyReleased
    {//GEN-HEADEREND:event_jTextField_SearchKeyReleased
        jTable.setModel(new DefaultTableModel(null, new Object[]
        {
            "ID", "Leasing ID", "Status", "Date", "Type", "Check Num", "Transaction"
        }));
        //Fill table with relevant results
        pl.fillPaymentLogJtable(jTable, jTextField_Search.getText());
    }//GEN-LAST:event_jTextField_SearchKeyReleased
    //Method to fill fields if entry selected by up down on keyboard
    private void jTableKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTableKeyReleased
    {//GEN-HEADEREND:event_jTableKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP
                || evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
            //Get info of entry
            rowIndex = jTable.getSelectedRow();
            jTextField_ID.setText(model.getValueAt(rowIndex, 0).toString());
            jTextField_LeasingID.setText(model.getValueAt(rowIndex, 1).toString());
            jTextField_Status.setText(model.getValueAt(rowIndex, 2).toString());
            jTextField_Type.setText(model.getValueAt(rowIndex, 4).toString());
            jTextField_Check.setText(String.valueOf(model.getValueAt(rowIndex, 5)));
            jTextField_Transact.setText(String.valueOf(model.getValueAt(rowIndex, 6)));
        }
        //Convert date
        Date date;
        try
        {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex,
                    3).toString());
            jDate_PaymentDate.setDate(date);
          //Handle errors
        } catch (ParseException ex)
        {
            Logger.getLogger(managePaymentLog.class.getName()).log(Level.SEVERE,
                    null, ex);
        }
    }//GEN-LAST:event_jTableKeyReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(managePaymentLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(managePaymentLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(managePaymentLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(managePaymentLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new managePaymentLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Remove;
    private com.toedter.calendar.JDateChooser jDate_PaymentDate;
    private javax.swing.JLabel jLabelPayment_Type;
    private javax.swing.JLabel jLabel_Check;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_LeasingID;
    private javax.swing.JLabel jLabel_PaymentDate;
    private javax.swing.JLabel jLabel_Search;
    private javax.swing.JLabel jLabel_Status;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_Transact;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField_Check;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_LeasingID;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_Status;
    private javax.swing.JTextField jTextField_Transact;
    private javax.swing.JTextField jTextField_Type;
    // End of variables declaration//GEN-END:variables
} //End managePaymentLog