package GUI;

/**
 *
 * @author Sherry Zhuang
 */

//Imports
import DB.renter;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.sun.glass.events.KeyEvent;

//Class to display manage renter page
public class manageRenter extends javax.swing.JFrame
{
    //Create instance
    renter r = new renter();
    DefaultTableModel model;
    int rowIndex;

    //Create form
    public manageRenter()
    {
        initComponents();
        //Fill table
        r.fillRenterJtable(jTable, "");
        //Set model
        model = (DefaultTableModel) jTable.getModel();
        //Set table attributes
        jTable.setRowHeight(30);
        jTable.setShowGrid(true);
        jTable.setGridColor(Color.blue);
        jTable.setSelectionBackground(Color.BLACK);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jLabel_FName = new javax.swing.JLabel();
        jLabel_LName = new javax.swing.JLabel();
        jLabel_IDProof = new javax.swing.JLabel();
        jLabel_Address = new javax.swing.JLabel();
        jTextField_FName = new javax.swing.JTextField();
        jTextField_LName = new javax.swing.JTextField();
        jTextField_IDProof = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jButton_Edit = new javax.swing.JButton();
        jButton_Remove = new javax.swing.JButton();
        jLabel_Search = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel_ID = new javax.swing.JLabel();
        jTextField_Search = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel_Title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_Title.setText("Manage Renter");

        jLabel_FName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_FName.setText("First Name");

        jLabel_LName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_LName.setText("Last Name");

        jLabel_IDProof.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_IDProof.setText("Identity Proof");

        jLabel_Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Address.setText("Address");

        jTextField_FName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_FName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_FNameKeyTyped(evt);
            }
        });

        jTextField_LName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_LName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_LNameKeyTyped(evt);
            }
        });

        jTextField_IDProof.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_IDProof.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextField_IDProofKeyTyped(evt);
            }
        });

        jTextArea_Address.setColumns(20);
        jTextArea_Address.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea_Address.setRows(5);
        jTextArea_Address.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextArea_AddressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_Address);

        jButton_Edit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Remove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Remove.setText("Remove");
        jButton_Remove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_RemoveActionPerformed(evt);
            }
        });

        jLabel_Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Search.setText("Search");

        jTextField_ID.setEditable(false);
        jTextField_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel_ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_ID.setText("ID");

        jTextField_Search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Search.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTextField_SearchKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "First Name", "Last Name", "Identity Proof", "Address"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTableMouseClicked(evt);
            }
        });
        jTable.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTableKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0)
        {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel_Title))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel_LName)
                                            .addComponent(jLabel_FName))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_LName)
                                            .addComponent(jTextField_FName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel_IDProof)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_IDProof, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel_Address)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(2, 2, 2))
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton_Remove)
                                .addGap(30, 30, 30)
                                .addComponent(jButton_Edit)
                                .addGap(24, 24, 24)))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel_Title)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FName)
                            .addComponent(jTextField_FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_LName)
                            .addComponent(jTextField_LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_IDProof)
                            .addComponent(jTextField_IDProof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Address)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Search)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Method to verify field
    public boolean verify()
    {
        if (jTextField_FName.getText().equals("")
                || jTextField_LName.getText().equals("")
                || jTextField_IDProof.getText().equals("")
                || jTextArea_Address.getText().equals("")
                || jTextField_ID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or More Empty Field(s).");
            return false;
        } else
        {
            return true;
        }
    }
    //Method to edit entry
    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_EditActionPerformed
    {//GEN-HEADEREND:event_jButton_EditActionPerformed
        //Get text of fields
        String fname = jTextField_FName.getText();
        String lname = jTextField_LName.getText();
        String idproof = jTextField_IDProof.getText();
        String address = jTextArea_Address.getText();
        int id = Integer.valueOf(jTextField_ID.getText());
        
        //Verify selection
        if (verify())
        {
            //Update data
            r.insertUpdateDeleteRenter('u', id, fname, lname, idproof, address);
            //Set text of fields after update
            jTextField_ID.setText("");
            jTextField_FName.setText("");
            jTextField_LName.setText("");
            jTextField_IDProof.setText("");
            jTextArea_Address.setText("");
            jTextField_Search.setText("");

            //Refresh table
            manageRenter.jTable.setModel(new DefaultTableModel(null, new Object[]
            {
                "ID", "First Name", "Last Name", "Identity Proof", "Address"
            }));
            r.fillRenterJtable(manageRenter.jTable, "");
        }
    }//GEN-LAST:event_jButton_EditActionPerformed
    //Method to remove entry
    private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_RemoveActionPerformed
    {//GEN-HEADEREND:event_jButton_RemoveActionPerformed
        //Verify selection
        if (jTextField_ID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No Renter Selected.");
        } else
        {
            int id = Integer.valueOf(jTextField_ID.getText());
            //Delete data
            r.insertUpdateDeleteRenter('d', id, null, null, null, null);
            r.fillRenterJtable(jTable, "");
            //Refresh table
            jTable.setModel(new DefaultTableModel(null, new Object[]
            {
                "ID", "First Name", "Last Name", "Identity Proof", "Address"
            }));
            r.fillRenterJtable(jTable, jTextField_Search.getText());
            
            //Set text of fields after delete
            jTextField_ID.setText("");
            jTextField_FName.setText("");
            jTextField_LName.setText("");
            jTextField_IDProof.setText("");
            jTextArea_Address.setText("");
            jTextField_Search.setText("");
        }
    }//GEN-LAST:event_jButton_RemoveActionPerformed
    //Method to validate and limit field
    private void jTextField_FNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_FNameKeyTyped
    {//GEN-HEADEREND:event_jTextField_FNameKeyTyped
        if (Character.isDigit(evt.getKeyChar())
                || jTextField_FName.getText().length() > 48)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_FNameKeyTyped
    //Method to validate and limit field
    private void jTextField_LNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_LNameKeyTyped
    {//GEN-HEADEREND:event_jTextField_LNameKeyTyped
        if (Character.isDigit(evt.getKeyChar())
                || jTextField_LName.getText().length() > 48)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_LNameKeyTyped
    //Method to validate and limit field
    private void jTextField_IDProofKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_IDProofKeyTyped
    {//GEN-HEADEREND:event_jTextField_IDProofKeyTyped
        if (Character.isDigit(evt.getKeyChar())
                || jTextField_IDProof.getText().length() > 48)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_IDProofKeyTyped
    //Method to limit field
    private void jTextArea_AddressKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextArea_AddressKeyTyped
    {//GEN-HEADEREND:event_jTextArea_AddressKeyTyped
        if (jTextArea_Address.getText().length() > 98)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextArea_AddressKeyTyped
    //Method to fill fields if entry clicked
    private void jTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableMouseClicked
    {//GEN-HEADEREND:event_jTableMouseClicked
        model = (DefaultTableModel) jTable.getModel();

        rowIndex = jTable.getSelectedRow();
        //Get info of entry
        jTextField_ID.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField_FName.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField_LName.setText(model.getValueAt(rowIndex, 2).toString());
        jTextField_IDProof.setText(model.getValueAt(rowIndex, 3).toString());
        jTextArea_Address.setText(model.getValueAt(rowIndex, 4).toString());

    }//GEN-LAST:event_jTableMouseClicked
    //Method to fill fields if entry selected by up down on keyboard
    private void jTableKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTableKeyReleased
    {//GEN-HEADEREND:event_jTableKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP
                || evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
            rowIndex = jTable.getSelectedRow();
            //Get info of entry
            jTextField_ID.setText(model.getValueAt(rowIndex, 0).toString());
            jTextField_FName.setText(model.getValueAt(rowIndex, 1).toString());
            jTextField_LName.setText(model.getValueAt(rowIndex, 2).toString());
            jTextField_IDProof.setText(model.getValueAt(rowIndex, 3).toString());
            jTextArea_Address.setText(model.getValueAt(rowIndex, 4).toString());
        }
    }//GEN-LAST:event_jTableKeyReleased
   //Method to search
    private void jTextField_SearchKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextField_SearchKeyReleased
    {//GEN-HEADEREND:event_jTextField_SearchKeyReleased
        jTable.setModel(new DefaultTableModel(null, new Object[]
        {
            "ID", "First Name", "Last Name", "Identity Proof", "Address"
        }));
        //Fill table with relevant results
        r.fillRenterJtable(jTable, jTextField_Search.getText());
    }//GEN-LAST:event_jTextField_SearchKeyReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(manageRenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(manageRenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(manageRenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(manageRenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new manageRenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Remove;
    private javax.swing.JLabel jLabel_Address;
    private javax.swing.JLabel jLabel_FName;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_IDProof;
    private javax.swing.JLabel jLabel_LName;
    private javax.swing.JLabel jLabel_Search;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextArea_Address;
    private javax.swing.JTextField jTextField_FName;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_IDProof;
    private javax.swing.JTextField jTextField_LName;
    private javax.swing.JTextField jTextField_Search;
    // End of variables declaration//GEN-END:variables
} //End manageRenter